#! /bin/zsh

~/.dotfiles/main/lemonbar.sh | lemonbar -B "#2b2b2b" -f "Font Awesome" -f "LiberationMono-Regular" &
feh --bg-fill ~/.dotfiles/main/moon_earth.jpg

wmname LG3D
sxhkd &
urxvt -e screen &
urxvt -e bonsai -ilt 0.25 &
urxvt -e cava &
urxvt -e htop &
bspc monitor -d I II III IV V

bspc config border_width         1
bspc config focused_border_color "#cee318"
bspc config normal_border_color "#9ac0cd"
bspc config window_gap          20

bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
bspc rule -a Matlab desktop='^3'
bspc rule -a Mathematica desktop='^3'
bspc rule -a Emacs state=tiled
