((magit-branch nil)
 (magit-commit nil)
 (magit-diff
  ("--no-ext-diff" "--stat")
  ("--no-ext-diff"))
 (magit-dispatch nil)
 (magit-fetch nil)
 (magit-merge nil)
 (magit-pull nil)
 (magit-push nil))
