#! /bin/zsh

~/.dotfiles/he-man/lemonbar.sh | lemonbar -B "#242422" -f "Font Awesome" -f "LiberationMono-Regular" &
feh --bg-fill ~/.dotfiles/he-man/he-man.jpg

wmname LG3D
sxhkd &
urxvt -e neofetch &
urxvt -e screen &
urxvt -e pipes &
urxvt -e htop &
bspc monitor -d I II III IV V

bspc config border_width         1
bspc config focused_border_color "#b2161c"
bspc config normal_border_color "#0e5a7c"
bspc config window_gap          20

bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
bspc rule -a MATLAB desktop='^3'


